Generalize ConstraintRef Model type
jump-dev/JuMP.jl pull request #2436
Opened 2021-01-26 16:52 UTC by guilhermebodin

Implements the suggestions on #2256

2021-01-26 17:26 UTC, guilhermebodin commented
Doctests fail because of the abstract type in cases like
```
Array{ConstraintRef{#s118,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape} where #s118<:AbstractModel,1}:
```
instead of 
```
Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
```

2021-01-26 19:58 UTC, odow requested changes
This is why the printing is failing.

2021-01-26 19:58 UTC, odow commented on src/constraints.jl
> +        constraint_ref_type = ConstraintRef{<:AbstractModel, _MOICON{f_type, set_type},
This needs to match the type of `model`. Either change it back to `Model`, or add a type parameter for `model`.

2021-01-26 19:58 UTC, odow commented on src/constraints.jl
> +        constraint_ref_type = ConstraintRef{<:AbstractModel, _MOICON{f_type, set_type}}
Ditto here.

2021-01-27 14:51 UTC, blegat commented on src/constraints.jl
> +1-element Array{ConstraintRef{<:AbstractModel,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
I don't understand why this is printed like that, it should be `Model`, not `<:AbstractModel`

2021-01-27 23:36 UTC, odow reviewed
It really only makes sense to relax type signatures if the internal function calls are also relaxed.

2021-01-27 23:36 UTC, odow commented on src/constraints.jl
> +function value(con_ref::ConstraintRef{<:AbstractModel, <:_MOICON}; result::Int = 1)
It doesn't really make sense to make this an `AbstractModel`, unless we also change the signature on `_constraint_primal`.

2021-01-27 23:36 UTC, odow commented on src/constraints.jl
> +function dual(con_ref::ConstraintRef{<:AbstractModel, <:_MOICON}; result::Int = 1)
Ditto here on `_constraint_dual`.

2021-01-28 08:53 UTC, odow approved these changes
Did CI run? This seems okay for now at least. @pulsipher, thoughts?

2021-01-28 16:30 UTC, pulsipher commented
This seems reasonable to me. It would seem that an extension implementing an `AbstractModel` would need to extend the underlying MOI methods then (e.g., `MOI.set`, `MOI.get`, etc.) right? It may be worth testing some of this explicitly via the CI tests that use `JuMPExtension.jl`, updating it to use `ConstraintRef`s with `MyModel` instead of `MyConstraintRef`.

2021-01-28 18:47 UTC, odow commented
They can also implement methods like `JuMP.dual` directly with a more-specific type. If they implement `backend`, things should work okay. 

I think this PR goes someway to reducing the number of methods they have to implement.

Feel free to suggest other changes that could make InfiniteOpt easier. But I don't think we should go through guessing which changes would make an extension easier if there is no downstream package using the changes.

2021-01-29 09:56 UTC, blegat approved these changes

2021-01-29 18:43 UTC, merged