Add the MINLP solver MAiNGO to the documentation
jump-dev/JuMP.jl pull request #3696
Opened 2024-03-01 15:28 UTC by MAiNGO-github

We have recently built a wrapper around our open-source global MINLP solver MAiNGO, which is is written in C++.
The wrapper initially took a lot of inspiration from the Baron.jl repository.

Looking at the [checklist](https://jump.dev/JuMP.jl/stable/developers/checklists/#Adding-a-new-solver-to-the-documentation), the conditions for including the solver in the documentation should be fulfilled.

We would be very excited to be included in the list of compatible solvers.

2024-03-01 19:57 UTC, odow commented
Nice! Let me take a look

2024-03-01 20:49 UTC, odow requested changes
I'm going to mark this as blocked by https://github.com/MAiNGO-github/MAiNGO.jl/issues/2, but it looks nice!

Pleased you figured out the Yggdrasil stuff :smile:

2024-03-08 17:56 UTC, MAiNGO-github commented
@odow 
I added the Github actions.
I also incorporated a recent improvement from Baron.jl

There are were spellchecking warnings. I fixed those that were correct. Some are caused by how our README is set up.
In case this is blocking or annoying, I would suggest not adding to docs/packages.toml, but only to the overview table.

2024-03-09 23:54 UTC, odow approved these changes

2024-03-09 23:55 UTC, merged